#!/usr/bin/env bash

export PYENV_ROOT="${XDG_CONFIG_HOME}/.pyenv"

[[ -d "${PYENV_ROOT}/bin" ]] && export PATH="${PYENV_ROOT}/bin:$PATH"

if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init -)"

  if pyenv commands | command grep -qx "virtualenvwrapper_lazy"; then
    pyenv virtualenvwrapper_lazy
  fi
fi

# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true

# Python startup file
export PYTHONSTARTUP="${HOME}/.pythonrc"
